export const DEVICE_LIST_REQUEST = 'DEVICE_LIST_REQUEST';
export const DEVICE_LIST_SUCCESS = 'DEVICE_LIST_SUCCESS';
export const DEVICE_LIST_FAIL = 'DEVICE_LIST_FAIL';

export const DEVICE_DETAILS_REQUEST = 'DEVICE_DETAILS_REQUEST';
export const DEVICE_DETAILS_SUCCESS = 'DEVICE_DETAILS_SUCCESS';
export const DEVICE_DETAILS_FAIL = 'DEVICE_DETAILS_FAIL';

export const DEVICE_SAVE_REQUEST = 'DEVICE_SAVE_REQUEST';
export const DEVICE_SAVE_SUCCESS = 'DEVICE_SAVE_SUCCESS';
export const DEVICE_SAVE_FAIL = 'DEVICE_SAVE_FAIL';

export const DEVICE_DELETE_REQUEST = 'DEVICE_DELETE_REQUEST';
export const DEVICE_DELETE_SUCCESS = 'DEVICE_DELETE_SUCCESS';
export const DEVICE_DELETE_FAIL = 'DEVICE_DELETE_FAIL';

export const MY_DEVICE_LIST_REQUEST = 'MY_DEVICE_LIST_REQUEST';
export const MY_DEVICE_LIST_SUCCESS = 'MY_DEVICE_LIST_SUCCESS';
export const MY_DEVICE_LIST_FAIL = 'MY_DEVICE_LIST_FAIL';
