export const LOG_LIST_REQUEST = 'LOG_LIST_REQUEST';
export const LOG_LIST_SUCCESS = 'LOG_LIST_SUCCESS';
export const LOG_LIST_FAIL = 'LOG_LIST_FAIL';

export const LOG_DETAILS_REQUEST = 'LOG_DETAILS_REQUEST';
export const LOG_DETAILS_SUCCESS = 'LOG_DETAILS_SUCCESS';
export const LOG_DETAILS_FAIL = 'LOG_DETAILS_FAIL';

export const LOG_SAVE_REQUEST = 'LOG_SAVE_REQUEST';
export const LOG_SAVE_SUCCESS = 'LOG_SAVE_SUCCESS';
export const LOG_SAVE_FAIL = 'LOG_SAVE_FAIL';

export const LOG_DELETE_REQUEST = 'LOG_DELETE_REQUEST';
export const LOG_DELETE_SUCCESS = 'LOG_DELETE_SUCCESS';
export const LOG_DELETE_FAIL = 'LOG_DELETE_FAIL';
